### ISSUE TITLE
Top Level Concepts should not be preloaded

### ISSUE THREAD

**Issue by simon-lammes** [simon-lammes/shared-concepts#6]
### Problem
Currently all top level concepts are loaded when the concept state is initialized. This means they are also leaded when the user does not navigate to the concepts page. Also the top level concepts do not have to  be loaded when the user just navigates to a specific concept like so: '/concepts/Neurology'.

### Task
The top level concepts should only be loaded when the user requests to see them by navigating to '/concepts'.

### Possible Procedure
- [x] In the concept page, check whether a concept key is provided in the url. If not, the user currently navigated to the top level concepts page.
- [x] In that case trigger the loading of the top level concepts. It would be nice if name of the action is changed so that it matches the naming convention of being passive. Suggestion: _TopLevelConceptsRequested_
- [x] You can verify the correct behavior by deleting localstorage and afterwards directly navigating to a url other than '/concepts'. When the network tab shows no backend calls for fetching top level concepts, you succeeded.
